---
title: "Visualization"
subtitle: "Part II"
author: "Ying Jin"
date: "2020/10/1"
output: github_document
---

```{r setup}
library(tidyverse)
library(patchwork)
```

## Load the weather data

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

## Remember this plot...?

```{r}
weather_df %>% 
  ggplot(aes(x = tmin,y=tmax,color = name)) +
  geom_point()
```

## Label

```{r}
weather_df %>% 
  ggplot(aes(x = tmin,y=tmax,color = name)) +
  geom_point(alpha = .5)+
  labs(
    title="Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maximum daily temperature (C)",
    caption = "Data from the rnoaa package,temperature in 2017"
  )
  
```

# Scales

Start with the same plot; x and y scales

```{r}
weather_df %>% 
  ggplot(aes(x = tmin,y=tmax,color = name)) +
  geom_point(alpha = .5)+
  labs(
    title="Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maximum daily temperature (C)",
    caption = "Data from the rnoaa package,temperature in 2017"
  ) +
  scale_x_continuous(
    breaks = c(-15,0,15),
    labels = c("-15 C","0","15 C")
  ) +
  scale_y_continuous(
    position = "right"
  )
```

Look at color scales

```{r}
weather_df %>% 
  ggplot(aes(x = tmin,y=tmax,color = name)) +
  geom_point(alpha = .5)+
  labs(
    title="Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maximum daily temperature (C)",
    caption = "Data from the rnoaa package,temperature in 2017"
  )+
  scale_color_hue(
    name = "Location",
    h = c(100,300))
```

Another way to modify color scale

```{r}
weather_df %>% 
  ggplot(aes(x = tmin,y=tmax,color = name)) +
  geom_point(alpha = .5)+
  labs(
    title="Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maximum daily temperature (C)",
    caption = "Data from the rnoaa package,temperature in 2017"
  ) +
  viridis::scale_color_viridis(
    name = "Loctation",
    discrete = TRUE
  )
```

## Themes

Shift the legend.

```{r}
weather_df %>% 
  ggplot(aes(x = tmin,y=tmax,color = name)) +
  geom_point(alpha = .5)+
  labs(
    title="Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maximum daily temperature (C)",
    caption = "Data from the rnoaa package,temperature in 2017"
  ) +
  viridis::scale_color_viridis(
    name = "Loctation",
    discrete = TRUE
  ) +
  theme(legend.position = "bottom")
```

Change the overall theme.

```{r}
weather_df %>% 
  ggplot(aes(x = tmin,y=tmax,color = name)) +
  geom_point(alpha = .5)+
  labs(
    title="Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maximum daily temperature (C)",
    caption = "Data from the rnoaa package,temperature in 2017"
  ) +
  viridis::scale_color_viridis(
    name = "Loctation",
    discrete = TRUE
  ) +
  theme_minimal() +
  theme(legend.position = "bottom")
```

theme_minimal is recommened, but there are other themes.

```{r}
weather_df %>% 
  ggplot(aes(x = tmin,y=tmax,color = name)) +
  geom_point(alpha = .5)+
  labs(
    title="Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maximum daily temperature (C)",
    caption = "Data from the rnoaa package,temperature in 2017"
  ) +
  viridis::scale_color_viridis(
    name = "Loctation",
    discrete = TRUE
  ) +
  ggthemes::theme_economist()
  
```

## Settng options

```{r,eval = FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot_cpntinuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viris_d
scale_fill_discrete = scale_fill_viridis_d
```

## Data args in 'geom'

```{r}
central_park = 
  weather_df %>% 
  filter(name == "CentralPark_NY")

waikiki =
  weather_df %>% 
  filter(name == "Waikiki_HA")

ggplot(data = waikiki,aes(x=date,y=tmax,color = name))+
  geom_point()+
  geom_line(data = central_park)



```

